Trolltampen/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Trolltampen.Repositories;
using Trolltampen.Models;
using Trolltampen.DAL;


namespace Trolltampen.Controllers
{
    public class ContactController : Controller
    {
         private IContactsRepository contactsRepo;
        public ContactController()
        {
            contactsRepo = new ContactsRepository(new TTDBContext());
        }
        public ContactController(IContactsRepository iContRepo)
        {
            contactsRepo = iContRepo;
        }
        protected override void Dispose(bool disposing)
        {
            contactsRepo.Dispose();
            base.Dispose(disposing);
        }
        //
        // GET: /Contact/
        public ActionResult Index()
        {
            return View(contactsRepo.GetFrontContacts());
        }
	}
}

Trolltampen/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Trolltampen.Controllers
{
    
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Navigation()
        {
            return View();
        }
    }
}

Trolltampen/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Trolltampen.DAL;
using Trolltampen.Models;
using Trolltampen.Repositories;

namespace Trolltampen.Controllers
{
    public class NewsController : Controller
    {
        INewsRepository newsRepo;
        public NewsController()
        {
            newsRepo = new NewsRepository(new TTDBContext());
        }

        public NewsController(INewsRepository iNewsRepo)
        {
            newsRepo = iNewsRepo;
        }

        protected override void Dispose(bool disposing)
        {
            newsRepo.Dispose();
            base.Dispose(disposing);
        }
        //
        // GET: /News/
        public ActionResult Index()
        {
            return View(newsRepo.GetNews());
        }
	}
}

Trolltampen/Views/Home/Index.cshtml
@{
    Layout = "~/Views/Shared/FrontLayout.cshtml";
}
<div id="inner-wrap" class=' main_page'>
    <div class='all-page-wrap'>
        <header id="top" role="banner">
            <div>
                <div class="logo col-xs-8"><img class='img-responsive' src="~/Content/img/logo.png"></div>
                <a class="nav-btn navbar-toggle" id="nav-open-btn" href="#nav">
                    <span class='menu_text pull-left'>MENY</span>
                    <div class='icon-set pull-right'>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </div>
                </a>
            </div>
        </header>

        <nav id="nav" role="navigation">
            @Html.Action("Navigation", "Home")
        </nav>

        <div class='content'>
            <h1 class='main_page_slogan'>
                Flermedialt dokumentasjonsprosjekt<br>
                om nyere kulturhistorie i Nord-Norge med<br>
                utgangspunkt i <span class='name'>JACK BERNTSEN</span>.<br>
            </h1>
        </div>
    </div>
</div>
<!--/#inner-wrap-->
<div class='footer'>
    <div class='author pull-left'>
        designed by <span class='designer'>Hipp Hurra</span> and developed by <span class='developer'>Pricom</span><br>
        copyright 2014 all rights reserved
    </div>
    <div class='soc_icons text-right pull-right'>
        <a href=""><img src="~/Content/img/fb_ico.png"></a>
        <a href=""><img src="~/Content/img/tweet_ico.png"></a>
    </div>
</div>

Trolltampen/Views/Home/Navigation.cshtml
<div class="block">
    <h2 class="block-title">Chapters</h2>
    <ul class='text-left'>
        <li class="is-active">
            <a href="@Url.Action("Index","Home")">Home</a>
        </li>
        <li>
            <a href="@Url.Action("Index","News")">News</a>
        </li>
        <li>
            <a href="@Url.Action("Index","Partners")">Partners</a>
        </li>
        <li>
            <a href="@Url.Action("Index","Contact")">Contact</a>
        </li>
    </ul>
    <a class="close-btn" id="nav-close-btn" href="#top">Return to Content</a>
</div>