Trolltampen/Controllers/FrontGalleryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Trolltampen.DAL;
using Trolltampen.Models;
using Trolltampen.Repositories;

namespace Trolltampen.Controllers
{
    [Authorize]
    public class FrontGalleryController : Controller
    {

        IGalleryRepository frontGallRepo;
        public FrontGalleryController()
        {
            frontGallRepo = new GalleryRepository(new TTDBContext());
        }

        public FrontGalleryController(IGalleryRepository igalRepo)
        {
            frontGallRepo = igalRepo;
        }
        //
        // GET: /FrontGallery/
        public ActionResult Index()
        {
            return View(frontGallRepo.GetFrontGallery());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateFrontGallery(FrontGalleryModel model)
        {
            if (ModelState.IsValid)
            {

            }
            return View("Index", model);
        }

        [HttpPost]
    [ValidateAntiForgeryToken]
        public ActionResult AddPhotoToFrontGallery(PhotoMediaModel model)
        {
            if (!string.IsNullOrEmpty(model.FileName)&&model.PhotoFile!=null)
            {
                frontGallRepo.AddPhotoToGallery(model);
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateOrderNum(FrontGalleryModel model)
        {
            frontGallRepo.UpdateOrderNum(model);
            return RedirectToAction("Index");
        }
        public ActionResult ActivateFrontPhoto(int pID, bool toActivate)
        {
            frontGallRepo.ToActive(pID, toActivate);
            return RedirectToAction("Index");
        }
        public ActionResult DeleteFrontPhoto(int pID)
        {
            frontGallRepo.DeleteFrontPhoto(pID);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            frontGallRepo.Dispose();
            base.Dispose(disposing);
        }
    }
}

Trolltampen/Views/FrontGallery/Index.cshtml
@model FrontGalleryModel
@{
    ViewBag.Title = "Front Gallery";
    Layout = "~/Views/Shared/TrolltampenLayout.cshtml";
    int index = 0;
    string id;
    string name;
    string hid;
    string hname;
    string imgid;
    string gItemId;
}
<div id="page-wrapper">
    <div id="photogallery" class="col-lg-12">
        <div>
            <h4>Photo gallery</h4>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                Add new photo
            </div>
            <div class="panel-body">
                @using (@Html.BeginForm("AddPhotoToFrontGallery", "FrontGallery", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()
                    <div class="col-md-8">
                        <div class="col-md-6">
                            <input type="file" class="form-control" id="photofile" name="PhotoFile" />
                            <input type="hidden" id="photofilename" name="FileName" />
                        </div>
                        <div class="col-md-6">
                            <input type="submit" class="btn btn-success" value="Add photo" />
                        </div>
                    </div>
                    <div id="delphoto" class="col-md-4" style="display:none">
                        <div class="col-md-6">
                            <img id="photoimg" class="img-responsive" style="display:none" />
                        </div>
                        <div class="col-md-6">
                            <input type="button" class="btn btn-default" value="Delete picture" />
                        </div>
                    </div>
                }
                <script>
                    InitiateMediaPhoto();
                </script>
            </div>
        </div>
        @using (Html.BeginForm("UpdateOrderNum","FrontGallery"))
        {
            @Html.AntiForgeryToken()
            <div class="panel panel-default">
                <div class="panel-heading">
                    <button type="submit" class="btn btn-warning">Update Galleery</button>
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover text-center" id="categoryTable">
                            <thead>
                                <tr>
                                    <th class="text-center">Image</th>
                                    <th class="text-center">Order</th>
                                    <th class="text-center">Active</th>
                                    <th class="text-center">Delete</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model.Photos.Gallery != null)
                                {
                                    foreach (var item in Model.Photos.Gallery.PhotoFiles)
                                    {
                                        gItemId = "galleryitem" + index.ToString();
                                        <tr class="form-group galleryitem" id="@gItemId">
                                            <td>
                                                <img height="90" src="~/Images/@Model.Photos.Gallery.PhotoFiles[index].FileName" />
                                            </td>
                                            <td>
                                                @Html.TextBoxFor(m => m.Photos.Gallery.PhotoFiles[index].OrderNum, new { type = "number", width = "30px" })
                                            </td>
                                            @if (Model.Photos.Gallery.PhotoFiles[index].IsActive)
                                            {
                                                <td>
                                                    <input type="button" class="btn btn-outline btn-success activeitem" data-url="@Url.Action("ActivateFrontPhoto", new { pID = @Model.Photos.Gallery.PhotoFiles[index].ID, toActivate = "false"})" value="Published" />
                                                </td>
                                            }
                                            else
                                            {
                                                <td>
                                                    <input type="button" class="btn btn-outline btn-warning activeitem" data-url="@Url.Action("ActivateFrontPhoto", new { pID = @Model.Photos.Gallery.PhotoFiles[index].ID, toActivate = "true"})" value="Publish" />
                                                </td>
                                            }
                                            <td>
                                                <input type="button" class="btn btn-outline btn-danger delitem" data-url="@Url.Action("DeleteFrontPhoto", new { pID = @Model.Photos.Gallery.PhotoFiles[index].ID})" data-name="Front photo" value="Delete" />
                                            </td>
                                        </tr>
                                        @Html.HiddenFor(m => Model.Photos.Gallery.PhotoFiles[index].ID)
                                            index++;
                                    }
                                }
                            </tbody>
                            @Html.HiddenFor(m => m.GalleryID)
                        </table>
                    </div>
                </div>
            </div>
        }
    </div>
    <script>
        InitiateList();
    </script>
</div>