Trolltampen/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Trolltampen.Repositories;
using Trolltampen.Models;
using Trolltampen.DAL;


namespace Trolltampen.Controllers
{
    public class ContactController : Controller
    {
         private IContactsRepository contactsRepo;
        public ContactController()
        {
            contactsRepo = new ContactsRepository(new TTDBContext());
        }
        public ContactController(IContactsRepository iContRepo)
        {
            contactsRepo = iContRepo;
        }
        protected override void Dispose(bool disposing)
        {
            contactsRepo.Dispose();
            base.Dispose(disposing);
        }
        //
        // GET: /Contact/
        public ActionResult Index()
        {
            return View(contactsRepo.GetFrontContacts());
        }
	}
}

Trolltampen/Controllers/ContactsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Trolltampen.Models;
using Trolltampen.DAL;
using Trolltampen.Repositories;

namespace Trolltampen.Controllers
{
    [Authorize]
    public class ContactsController : Controller
    {
        private IContactsRepository contactsRepo;
        public ContactsController()
        {
            contactsRepo = new ContactsRepository(new TTDBContext());
        }
        public ContactsController(IContactsRepository iContRepo)
        {
            contactsRepo = iContRepo;
        }

        // GET: /Addresses/
        public ActionResult Index()
        {
            return View(contactsRepo.GetAllContacts().ToList());
        }


        // GET: /Addresses/Create
        public ActionResult Create()
        {
            ContactModel model = new ContactModel();
            model.Contact.MediaTypeID = 1;
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ContactModel model)
        {
            if (!ModelState.IsValid) return View(model);

            model.Contact.CreatedOn = DateTime.Now;
            contactsRepo.CreateContact(model);
            return RedirectToAction("Index");

        }

        // GET: /Addresses/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ContactModel model = contactsRepo.GetContactForEdit((int)id);
            if (model == null)
            {
                return HttpNotFound();
            }
            return View(model);
        }

        // POST: /Addresses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ContactModel model)
        {
            if (!ModelState.IsValid) return View(model);
            contactsRepo.UpdateContact(model);
            return RedirectToAction("Index");
        }

        // GET: /Addresses/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            contactsRepo.DeleteContact((int)id);
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateOrder(IEnumerable<Contact> contacts)
        {
            contactsRepo.UpdateContactOrderNum(contacts);
            return RedirectToAction("Index");
        }

        public ActionResult ActivateContact(int id, bool toActivate)
        {
            contactsRepo.UpdateContactStatus(id, toActivate);
            return RedirectToAction("Index");

        }

        protected override void Dispose(bool disposing)
        {
            contactsRepo.Dispose();
            base.Dispose(disposing);
        }
    }
}

Trolltampen/Views/Contacts/Create.cshtml
@model Trolltampen.Models.ContactModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/TrolltampenLayout.cshtml";
}

<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Add contact</h1>
        </div>
    </div>
    @using (Html.BeginForm("Create", "Contacts", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Address</h4>
            <hr />
            @Html.ValidationSummary(true)
            <div class="form-group">
                @Html.LabelFor(model => model.Contact.FirstName, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Contact.FirstName)
                    @Html.ValidationMessageFor(model => model.Contact.FirstName)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Contact.LastName, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Contact.LastName)
                    @Html.ValidationMessageFor(model => model.Contact.LastName)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Contact.Position, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Contact.Position)
                    @Html.ValidationMessageFor(model => model.Contact.Position)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Contact.Email, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Contact.Email)
                    @Html.ValidationMessageFor(model => model.Contact.Email)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Contact.PhoneNum, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Contact.PhoneNum)
                    @Html.ValidationMessageFor(model => model.Contact.PhoneNum)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Contact.Description, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.Contact.Description)
                    @Html.ValidationMessageFor(model => model.Contact.Description)
                </div>
            </div>
            @Html.HiddenFor(m => m.Contact.MediaTypeID)
            <div id="photomedia" class="form-group" style="">
                <label class="control-label col-md-2">Select photo file</label>
                <div class="col-md-10">
                    <input type="file" class="form-control" id="photofile" name="Content.Photo.PhotoFile" />
                    <input type="hidden" id="photofilename" name="Content.Photo.FileName">
                </div>
                <div class="form-group">
                    <img id="photoimg" width="180" height="120" style="display:none" />
                </div>
                <div class="form-group">
                    <input type="button" class="btn btn-default" id="delphoto" style="display:none" value="Delete picture" />
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>
<script>
    InitiateCreatingContact();
</script>

Trolltampen/Views/Contacts/Delete.cshtml
@model Trolltampen.Models.Contact

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/TrolltampenLayout.cshtml";
}

<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Delete</h1>
        </div>
    </div>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Address</h4>
        <hr />
        <dl class="dl-horizontal">

            <dt>
                @Html.DisplayNameFor(model => model.FirstName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.FirstName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.LastName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.LastName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Email)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Email)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</div>

Trolltampen/Views/Contacts/Details.cshtml
@model Trolltampen.Models.Contact

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/TrolltampenLayout.cshtml";
}

<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">address details</h1>
        </div>
    </div>

    <div>
        <h4>Address</h4>
        <hr />
        <dl class="dl-horizontal">
            

            <dt>
                @Html.DisplayNameFor(model => model.FirstName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.FirstName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.LastName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.LastName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Email)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Email)
            </dd>

        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</div>

Trolltampen/Views/Contacts/Edit.cshtml
@model Trolltampen.Models.ContactModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/TrolltampenLayout.cshtml";
}

<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">@Model.Contact.FirstName @Model.Contact.LastName</h1>
        </div>
    </div>
    @using (Html.BeginForm("Edit", "Contacts", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Address</h4>
            <hr />
            @Html.ValidationSummary(true)
            <div class="form-group">
                @Html.LabelFor(model => model.Contact.FirstName, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Contact.FirstName)
                    @Html.ValidationMessageFor(model => model.Contact.FirstName)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Contact.LastName, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Contact.LastName)
                    @Html.ValidationMessageFor(model => model.Contact.LastName)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Contact.Position, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Contact.Position)
                    @Html.ValidationMessageFor(model => model.Contact.Position)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Contact.Email, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Contact.Email)
                    @Html.ValidationMessageFor(model => model.Contact.Email)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Contact.PhoneNum, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Contact.PhoneNum)
                    @Html.ValidationMessageFor(model => model.Contact.PhoneNum)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Contact.Description, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.Contact.Description)
                    @Html.ValidationMessageFor(model => model.Contact.Description)
                </div>
            </div>

            @{string photoname = Model.Content.Photo == null ? Url.Content("~/Content/img/grey_img.png") :Url.Content("~/Images/") + Model.Content.Photo.FileName;    }
            <div id="photomedia">
                <div class="form-group" style="">
                    <label class="control-label col-md-4">Select photo file</label>
                    <div class="col-md-6">
                        <input type="file" class="form-control" id="photofile" name="Content.Photo.PhotoFile" />
                        @Html.Hidden("Content.Photo.FileName", photoname, new { id = "photofilename" })
                    </div>
                    <div class="form-group">

                        <img id="photoimg" width="180" height="120" style="display:block" src="@photoname" />
                    </div>
                    <div class="form-group">
                        <input type="button" class="btn btn-default" id="delphoto" style="display:block" value="Delete picture" />
                    </div>
                </div>
            </div>
            <script>
                InitiateEditPhoto();
            </script>
            @Html.HiddenFor(m=>m.Contact.ID)
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Update" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>

Trolltampen/Views/Contacts/Index.cshtml
@model List<Trolltampen.Models.Contact>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/TrolltampenLayout.cshtml";
}

<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Trolltampen contacts</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            @using (Html.BeginForm("UpdateOrder", "Contacts"))
            {
                @Html.AntiForgeryToken()
                <div class="panel panel-default">
                    <div class="panel-heading">

                        <button id="createnew" data-url="@Url.Action("Create")" type="button" class="btn btn-success">New...</button>
                        <button type="submit" class="btn btn-warning">Update order</button>

                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered table-hover" id="categoryTable">
                                <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Position</th>
                                        <th>Order</th>
                                        <th>Active</th>
                                        <th>Edit</th>
                                        <th>Delete</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @for (var i = 0; i < Model.Count; i++)
                                    {
                                        <tr class="odd gradeX">
                                            <td>@Model[i].FirstName @Model[i].LastName</td>
                                            <td>
                                                @Model[i].Position
                                            </td>
                                            <td>
                                                @Html.TextBoxFor(m => m[i].OrderNum, new { type = "number", width = "30px" })
                                            </td>
                                            @if (Model[i].IsActive)
                                            {
                                                <td>
                                                    <input type="button" class="btn btn-outline btn-success activeitem" data-url="@Url.Action("ActivateContact", new { id = Model[i].ID, toActivate="false"})" value="Published" />
                                                </td>
                                            }
                                            else
                                            {
                                                <td>
                                                    <input type="button" class="btn btn-outline btn-warning activeitem" data-url="@Url.Action("ActivateContact", new { id = Model[i].ID, toActivate="true"})" value="Publish" />
                                                </td>
                                            }
                                            <td>
                                                <input type="button" class="btn btn-outline btn-warning edititem" data-url="@Url.Action("Edit", new { id = Model[i].ID })" value="Edit" />
                                            </td>
                                            <td>
                                                <input type="button" class="btn btn-outline btn-danger delitem" data-url="@Url.Action("Delete", new {id= Model[i].ID})" data-name="@Model[i].FirstName @Model[i].LastName" value="Delete" />
                                            </td>
                                        </tr>
                                        @Html.HiddenFor(m => Model[i].ID)
                                    }
                                </tbody>
                            </table>
                        </div>
                        <!-- /.table-responsive -->
                    </div>
                    <!-- /.panel-body -->
                </div>
        <!-- /.panel -->
            }
        </div>
        <!-- /.col-lg-12 -->
    </div>
</div>
<script>
    InitiateContactList();
</script>